### ISSUE TITLE
The system has currently insufficient resources to process this request. 

### ISSUE THREAD

**Issue by klimeto** [inspire-eu-validation/ets-repository#97] opened 2017-09-30 11:31 UTC
Trying to execute any test results in the following error:

**Test Run initialization failure
The system has currently insufficient resources to process this request. Please wait a few minutes and try again. If the problem persists, please contact the ETF system administrator of the server.**

When checking the system status via API (/v2/status.json) receiving the following response:  
**Less then 5 GB disk space available,Less then 13% disk space available**

And status **MAJOR** which based on API docs indicates that framework internal errors were thrown during the last 2 minutes.

Any idea how to make the validator available for users again?
Thanks,
Tomas

**Comment by cportele** [comment] 2017-10-02 10:00
This check has been added in early August (see https://github.com/interactive-instruments/etf-webapp/issues/119) to reduce the cases where test runs could overload then system.

I.e., to change the status, the disk space in the deployment needs to be cleaned or enlarged. Michael, therefore, I assign this issue to you.

A related thought: Maybe it would make sense to activate the "contact" button in the UI so that issues in the deployment could be reported via a direct email. Issues in the software or the ETSs would continue to be reported in the GitHub repositories. The button can be activated by setting the property "etf.meta.contact.text" to a HTML fragment. See the [admin documentation](http://docs.etf-validator.net/v2.0/Admin_manuals/index.html#_etf_configuration).

**Comment by michellutz** [comment] 2017-10-03 07:14
Thanks. It think activating the button is a good idea. 
We are also currently investigating the root causes for the resource issues.
@robsgnao

**Comment by alkrus** [comment] 2017-10-31 14:41
The same issue is back again rendering the validator unavailable to users. Who can be kind to take a look at it?
Thanks!

**Comment by ahock-bkg** [comment] 2017-11-02 08:59
We are also facing this problem - the validator is more or less unavailable sind two days...

**Comment by michellutz** [comment] 2017-11-02 09:32
Sorry for the issue. We are looking into it.

**Comment by michellutz** [comment] 2017-11-02 13:46
The application is back up and running (on the latest stable release and with additional memory). Sorry again for the inconvenience.

**Closed by michellutz** 2017-11-02 13:46 UTC
Labels: Type: Question

**Comment by ahock-bkg** [comment] 2017-11-03 12:31
Thanks for the fast reply! There is still a problem with the validation - I guess in dependency to the source of this issue. The error we're receiving from time to time:
Test Run initialization failure
Die Datei konnte nicht heruntergeladen werden: 5 GB

**Comment by jonherrmann** [comment] 2017-11-03 13:06
There is an error in the output of the error message for which we have created an issue here:
https://github.com/interactive-instruments/etf-webapp/issues/130

This instance is configured to only accept ZIP files that do not exceed 5GB extraction size, so that the instance is not blocked by a few users. You can either split your ZIP files and run multiple test runs or you must set up a local instance in your organisation.

**Comment by ahock-bkg** [comment] 2017-11-03 13:11
I did not upload a zip file. I pasted an url and the response xml is 652 lines long with a size of 35 KB

**Comment by jonherrmann** [comment] 2017-11-03 13:25
Also other errors will be masked by this issue if the download fails.

Can you paste the URL here? Or mail it to ```etf at interactive-instruments dot de```

**Comment by OscarD31** [comment] 2017-11-15 07:20
I'm getting the error in the public deployment:

http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/v2/status

> ["Less then 5 GB disk space available","Less then 13% disk space available"]}

**Comment by fabiovinci** [comment] 2018-10-10 11:42
I'm trying to validate some metadata but I receive, since yesterday, the following error message "Upload failed - The system has currently insufficient resources to process this request......".
Could you please verify?
Thanks,
Fabio

**Comment by michellutz** [comment] 2018-10-11 16:09
@fabiovinci  We are looking into this issue. It seems that we need to fix the processes that should be regularly cleaning up storage.

**Comment by michellutz** [comment] 2018-10-12 07:10
The issue has been resolved. The system is back to normal.
