### ISSUE TITLE
StoredQuery contains all needed parameters, validator evaluates as error

### ISSUE THREAD

**Issue by MichalMed** [inspire-eu-validation/ets-repository#87] opened 2017-08-31 11:51 UTC
In validation http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/v2/TestRuns/EIDeb3dfb77-d410-40d0-8796-e5e562ea9e7f.html of WFS for pre-defined files we got an error on test "DescribeStoredQueries response does not contain at least one StoredQuery with the parameters 'CRS', 'DataSetID' , 'DataSetIdNamespace', 'Language', to download the entire INSPIRE dataset.". It does, but it contains additional optional parameter "zipped". It determines if the file is downloaded as zip or not. Default setting is false, even withou the presence of the parameter. However, validator evaluates that as an error.

**Comment by jonherrmann** [comment] 2017-08-31 12:02
The parameter name **language** is not found, as it begins with a lower case character. Required is a parameter ```Language```.

Btw, I noticed that the CRS parameter is not checked in the test ( https://github.com/inspire-eu-validation/ets-repository/issues/88 ).

**Comment by MichalMed** [comment] 2017-09-01 08:47
Now it looks like the whole service throws an error. I swear i have not changed anything but l in language. You have probably changed something in the validator?

**Comment by jonherrmann** [comment] 2017-09-01 09:14
The validator has not been changed. Please provide the URL to the test report next time, thanks.

http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/v2/TestRuns/EIDc3be935c-f169-4a20-b5fd-b4a43e55712d.html#EID3ca70328-015e-1000-9454-6f4853c6f34f

The issue is more technical and only shown as attachment "Message.2" when you switch to "All details":
http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp//v2/TestTaskResults/EID76bd8311-3926-4fd7-bcc7-2d829abba91f/Attachments/EID0d6bd002-c0e3-4928-85a9-dff0fe53d742

This is obviously not the best solution (we will think about what can be changed).

When you check your DescribeFeatureType response:
http://services.cuzk.cz/wfs/inspire-cp-wfs.asp?OUTPUTFORMAT=application%2Fgml%2Bxml%3Bversion%3D3.2&REQUEST=DescribeFeatureType&SERVICE=wfs&VERSION=2.0.0

you will see that the FeatureType namespace provided in the GetCapabilities is different:
http://services.cuzk.cz/wfs/inspire-cp-wfs.asp?REQUEST=GetCapabilities&SERVICE=wfs&VERSION=2.0.0

http://inspire.ec.europa.eu/schemas/cp/3.0 vs http://inspire.ec.europa.eu/schemas/cp/4.0

**Closed** 2018-08-28 12:03 UTC
Labels: Type: Question
