### ISSUE TITLE
GML validation issues

### ISSUE THREAD

**Issue by MarieLambois** [inspire-eu-validation/ets-repository#32] opened 2017-02-08 14:31 UTC
We have tested the ML validator with a (non-INSPIRE compliant) GML file created with ogr2ogr tools. The file is in the zip enclosed.
We have noticed 2 errors that do not seem justified. 

The dataset has 1 file(s) with errors for this assertion.
XML document 'r_site_classe_r52.gml': The root element is not a GML feature and not one of the recognised feature collections: wfs:FeatureCollection (WFS 2.0), gml:FeatureCollection (GML 3.2) or base:SpatialDataSet (INSPIRE Base schema 3.2 or 3.3). The name of the root element is 'FeatureCollection' in namespace 'http://ogr.maptools.org/'. It is recommended to use the WFS 2.0 feature collection element in INSPIRE.
-> This type inherits from gmf:FeatureCollection :
    <xs:element name="FeatureCollection" type="ogr:FeatureCollectionType" substitutionGroup="gml:_FeatureCollection"/>
        <xs:complexType name="FeatureCollectionType">
                <xs:complexContent>
                        <xs:extension base="gml:AbstractFeatureCollectionType">
                                <xs:attribute name="lockId" type="xs:string" use="optional"/>
                                <xs:attribute name="scope" type="xs:string" use="optional"/>
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>
        
XML document 'r_site_classe_r52.gml': 1:222: schema_reference.4: Failed to read schema document 'r_site_classe_r52.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
-> The root is xs:schema in this schema which is also acceptable as the namespace name is not normative. 
[r_site_classe_r52.zip](https://github.com/inspire-eu-validation/ets-repository/files/760882/r_site_classe_r52.zip)

**Comment by cportele** [comment] 2017-02-08 17:39
Regarding the first error: All the GML related tests, including the basic root element test, are only applicable to data meeting the interoperability requirements ("Interoperable data sets in GML"), i.e. are encoded using the INSPIRE GML application schemas. There are no testable rules for data in the source format. While this file uses GML, it is a different version of GML (2.1.2) and a different application schema.

Regarding "Failed to read schema document 'r_site_classe_r52.xsd'": The issue is not the namespace prefix, but the local XSD reference. References to XML Schema documents must be absolute HTTP URIs, i.e. available on a public web server. 

(All files in uploaded archives that do not end in .xml or .gml are ignored as files that include features should have one of these two extensions. This is something we need to make clear in the documentation.)

**Comment by cportele** [comment] 2017-03-17 14:43
>This is something we need to make clear in the documentation.

This will be addressed as part of https://github.com/interactive-instruments/etf-webapp/issues/72

**Comment by cportele** [comment] 2017-06-13 07:37
Closing as https://github.com/interactive-instruments/etf-webapp/issues/71 has been closed.

**Closed by cportele** 2017-06-13 07:37 UTC
Labels: progress: in progress
